In [1]:
#An example program to calculate Variance of a given data set
#No relation to OOPs
#YOU CAN SKIP THE PROG AND MOVE AHEAD
vac_nums = [0,0,0,0,0,1,1,1,1,1,1,1,1,2,2,2,2,3,3,3]

#CAL OF MEAN
mean = (sum(vac_nums))/20
#print(mean)
n = 0
sum_of_squared_diff = 0

#CAL OF SUM OF DIFFERENCE 
while n < len(vac_nums):
    sum_of_squared_diff += ((vac_nums[n] - mean)**2)
    n+=1 
    
print(sum_of_squared_diff)

#CAL VARIANCE

variance = sum_of_squared_diff/20
print(variance)

19.75
0.9875


In [2]:
#No relation to OOPs
#YOU CAN SKIP THE PROG AND MOVE AHEAD
#Basketball Players
#Calculate the number of players 
#in the range of Standard deviation from mean.

#importing math inbuilt function
import math

players = [180, 172, 178, 185, 190, 195, 192, 200, 210, 190]

#CAL MEAN

mean = sum(players)/10
#print(mean)

#CAL SUM OF SQUARED VALUES OF DIFFERENCE
#sum_of_sq_val_of_diff

sq_of_sum_of_diff = 0
n = 0

while n < len(players):
    sq_of_sum_of_diff += ((players[n] - mean)**2)
    n += 1
    
#print(sq_of_sum_of_diff)

#CAL VARIANCE
variance = sq_of_sum_of_diff/len(players)
#print(variance)

#CAL STANDARD DEVIATION
std_deviation = math.sqrt(variance)
#print(std_deviation)

#CAL NO. OF PLAYERS IN RANGE OF STANDARD DEVIATION AND MEAN
upper_value = mean + std_deviation
lower_value = mean - std_deviation
#print(upper_value, lower_value)

num_of_players = 0
for n in players:
    if n > lower_value and n < upper_value:
        num_of_players += 1
    
print('There are '+str(num_of_players)+' players in range of standard deviation and mean')

There are 6 players in range of standard deviation and mean


In [3]:
#Given an array that holds square footage data for houses on a 
#particular street. A new nouse has been constructed on that street. 
#Modify program to take the house value as input, add it to array, 
#output the array sorted in ascending order.

import numpy as np

data = np.array([1000, 2500, 1400, 1800, 900, 4200, 2200, 1900, 3500])

new_val = int(input("Enter the house data: "))

data = np.append(data, new_val)

#data = np.sort(data)

print(np.sort(data))

Enter the house data: 1120
[ 900 1000 1120 1400 1800 1900 2200 2500 3500 4200]


In [4]:
#Given an array the occupancy of seats in a movie theater. 
#A seat marked with 1 is occupied, while one marked 0 is free. 
#However, the array is 1 D. Transform into 2D array. 
#Each row would contain 5 seats and there are total 30 seats. 
#Rehape the array into the corresponding shape and output the row which
#is taken form the user.

import numpy as np

data = np.array([1,1,0,0,1,0,0,0,0,0,1,1,1,1,1,1,0,1,0,1,1,1,1,0,0,0,1,1,1,0])

seats = data.reshape(6,5)
print(seats)

row = int(input())

print(seats[row])

[[1 1 0 0 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [1 0 1 0 1]
 [1 1 1 0 0]
 [0 1 1 1 0]]
4
[1 1 1 0 0]


# Write a program to count the number of digits of a given number.

Sample Input 1:
345

Sample Output 1:
3

Sample Input 2:
56

Sample Output 2:
2

## Pseudo Code
1) taking input from user

2) storing the input in a variable

3) converting the input to integer

a = int(input)

4) counting the number of digits in the input

5) storing that answer in a variable
ans = len(a)

6) printing the variable for final answer

print(ans)

In [6]:
a = input("Enter a number: ")
ans = len(a)
print(ans)

Enter a number: 1982884
7


# Find given number is a digit in a number using Python
Get a number and a digit and find whether the digit is occurred in the number.

Sample Input 1:

Enter the number: 234

Enter the Digit : 4

Sample Output 1:

4 is occurred in 234

Sample Input 2:

Enter the number: 974

Enter the Digit : 3

Sample Output 2:

3 is not occurred in 974

## Pseudo Code

1) take number input form user

2) store it in variable (a)

3) ask user for another digit input

4) store it in another variable (b)

5) check wheather b is in a using if loop

    if b in a:
    
        print(b occurs in a)
        
    else
        
        pass

In [16]:
num = int(input("Enter a number: "))
digit = int(input("Enter a digit to check: "))

if digit in range(num):
    print(f"{digit} occurs in {num}")
else:
    print("Hello")

Enter a number: 12
Enter a digit to check: 11
11 occurs in 12


In [16]:
#Multiples of 3 and 5
#You are given a task to find all the whole numbers
#below 100 that are multiples of 3 and 5. Create an array
#of numbers below 100 that are multiples of both 3 and 5 and output it.

import numpy as np

x = np.arange(0, 101)
#print(len(x))
y = np.array([])
n = 0
m = 0

for n in x:
    if n%3 == 0 and n%5 == 0:
        np.insert(y, y[m], n )
        m+=1
        n+=1

#print(x[x%3==0])
#print(x[x%3==0] & [x%5==0])

IndexError: index 0 is out of bounds for axis 0 with size 0

### You get an array of numbers, return the sum of all of the positives ones.

Example [1,-4,7,12] => 1 + 7 + 12 = 20

Note: if there is nothing to sum, the sum is default to 0.

In [ ]:
def positive_sum(arr):
    
    return 0